name: Israel covid child health report CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t health-report-bot -f Dockerfile .
      - name: Tags
        run: |
          docker tag health-report-bot ${{ secrets.DOCKER_USER }}/health-report-bot:${{ github.sha }}
          docker tag health-report-bot ${{ secrets.DOCKER_USER }}/health-report-bot:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/health-report-bot:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/health-report-bot:latest
